// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzdJ7Ildq-8Cr4f5nhRr-JZLt50v1nM6I',
    appId: '1:659158137686:web:e9adc239ad68e9d8f0f4f7',
    messagingSenderId: '659158137686',
    projectId: 'message-board-5bf35',
    authDomain: 'message-board-5bf35.firebaseapp.com',
    storageBucket: 'message-board-5bf35.firebasestorage.app',
    measurementId: 'G-JF2G8DMW9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF-q9Yzu7-JGr59g1iHAz3zpt-wotLZcA',
    appId: '1:659158137686:android:d2c43acaec39d399f0f4f7',
    messagingSenderId: '659158137686',
    projectId: 'message-board-5bf35',
    storageBucket: 'message-board-5bf35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATwveFR8T4yWSAjV-_8gdVv-XzrEtTdYc',
    appId: '1:659158137686:ios:19e80924e50c73fcf0f4f7',
    messagingSenderId: '659158137686',
    projectId: 'message-board-5bf35',
    storageBucket: 'message-board-5bf35.firebasestorage.app',
    iosBundleId: 'com.example.messageBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATwveFR8T4yWSAjV-_8gdVv-XzrEtTdYc',
    appId: '1:659158137686:ios:19e80924e50c73fcf0f4f7',
    messagingSenderId: '659158137686',
    projectId: 'message-board-5bf35',
    storageBucket: 'message-board-5bf35.firebasestorage.app',
    iosBundleId: 'com.example.messageBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzdJ7Ildq-8Cr4f5nhRr-JZLt50v1nM6I',
    appId: '1:659158137686:web:1aa8142e14ba0447f0f4f7',
    messagingSenderId: '659158137686',
    projectId: 'message-board-5bf35',
    authDomain: 'message-board-5bf35.firebaseapp.com',
    storageBucket: 'message-board-5bf35.firebasestorage.app',
    measurementId: 'G-44SPFSDQL0',
  );
}
